/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace DeltaVSoft.RCFProto {

using System;
using System.Runtime.InteropServices;

/// <summary>
/// Represents a HTTPS endpoint. 
/// </summary>
public class HttpsEndpoint : TcpEndpoint {
  private HandleRef swigCPtr;

  internal HttpsEndpoint(IntPtr cPtr, bool cMemoryOwn) : base(RCFProtoPINVOKE.HttpsEndpoint_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(HttpsEndpoint obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~HttpsEndpoint() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          RCFProtoPINVOKE.delete_HttpsEndpoint(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  /// <summary>
  /// Constructs an HTTPS endpoint on the given port number. 
  /// </summary>
  public HttpsEndpoint(int port) : this(RCFProtoPINVOKE.new_HttpsEndpoint__SWIG_0(port), true) {
    if (RCFProtoPINVOKE.SWIGPendingException.Pending) throw RCFProtoPINVOKE.SWIGPendingException.Retrieve();
  }

  /// <summary>
  /// Constructs an HTTPS endpoint on the given IP address and port number. 
  /// </summary>
  public HttpsEndpoint(string ip, int port) : this(RCFProtoPINVOKE.new_HttpsEndpoint__SWIG_1(ip, port), true) {
    if (RCFProtoPINVOKE.SWIGPendingException.Pending) throw RCFProtoPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
