/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace DeltaVSoft.RCFProto {

using System;
using System.Runtime.InteropServices;

/// <summary>
/// Represents a HTTP endpoint. 
/// </summary>
public class HttpEndpoint : TcpEndpoint {
  private HandleRef swigCPtr;

  internal HttpEndpoint(IntPtr cPtr, bool cMemoryOwn) : base(RCFProtoPINVOKE.HttpEndpoint_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(HttpEndpoint obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~HttpEndpoint() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          RCFProtoPINVOKE.delete_HttpEndpoint(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  /// <summary>
  /// Constructs an HTTP endpoint on the given port number. 
  /// </summary>
  public HttpEndpoint(int port) : this(RCFProtoPINVOKE.new_HttpEndpoint__SWIG_0(port), true) {
    if (RCFProtoPINVOKE.SWIGPendingException.Pending) throw RCFProtoPINVOKE.SWIGPendingException.Retrieve();
  }

  /// <summary>
  /// Constructs an HTTP endpoint on the given IP address and port number. 
  /// </summary>
  public HttpEndpoint(string ip, int port) : this(RCFProtoPINVOKE.new_HttpEndpoint__SWIG_1(ip, port), true) {
    if (RCFProtoPINVOKE.SWIGPendingException.Pending) throw RCFProtoPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
