/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace DeltaVSoft.RCFProto {

using System;
using System.Runtime.InteropServices;

/// <summary>
/// Use this class to load a certificate in .pem format. Only applicable to OpenSSL. 
/// </summary>
public class PemCertificate : Certificate {
  private HandleRef swigCPtr;
  private bool swigCMemOwnDerived;

  internal PemCertificate(IntPtr cPtr, bool cMemoryOwn) : base(RCFProtoPINVOKE.PemCertificate_SWIGSmartPtrUpcast(cPtr), true) {
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(PemCertificate obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~PemCertificate() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwnDerived) {
          swigCMemOwnDerived = false;
          RCFProtoPINVOKE.delete_PemCertificate(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  /// <summary>
  /// Loads a .pem certificate, using the given file path and password. 
  /// </summary>
  public PemCertificate(string pathToCert, string password) : this(RCFProtoPINVOKE.new_PemCertificate__SWIG_0(pathToCert, password), true) {
    if (RCFProtoPINVOKE.SWIGPendingException.Pending) throw RCFProtoPINVOKE.SWIGPendingException.Retrieve();
  }

  public PemCertificate(string pathToCert) : this(RCFProtoPINVOKE.new_PemCertificate__SWIG_1(pathToCert), true) {
    if (RCFProtoPINVOKE.SWIGPendingException.Pending) throw RCFProtoPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
