/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace DeltaVSoft.RCFProto {

using System;
using System.Runtime.InteropServices;

/// <summary>
/// Use this class to load a certificate from .pfx format. Only applicable to Schannel. 
/// </summary>
public class PfxCertificate : Win32Certificate {
  private HandleRef swigCPtr;
  private bool swigCMemOwnDerived;

  internal PfxCertificate(IntPtr cPtr, bool cMemoryOwn) : base(RCFProtoPINVOKE.PfxCertificate_SWIGSmartPtrUpcast(cPtr), true) {
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(PfxCertificate obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~PfxCertificate() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwnDerived) {
          swigCMemOwnDerived = false;
          RCFProtoPINVOKE.delete_PfxCertificate(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  /// <summary>
  /// Loads a certificate from a .pfx file, using the given file path, password and certificate name. 
  /// </summary>
  public PfxCertificate(string pathToCert, string password, string certName) : this(RCFProtoPINVOKE.new_PfxCertificate(pathToCert, password, certName), true) {
    if (RCFProtoPINVOKE.SWIGPendingException.Pending) throw RCFProtoPINVOKE.SWIGPendingException.Retrieve();
  }

  /// <summary>
  /// Adds the certificate to the given Windows certificate store. 
  /// </summary>
  public void AddToStore(Win32CertificateLocation certStoreLocation, Win32CertificateStore certStore) {
    RCFProtoPINVOKE.PfxCertificate_addToStore(swigCPtr, (int)certStoreLocation, (int)certStore);
    if (RCFProtoPINVOKE.SWIGPendingException.Pending) throw RCFProtoPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
