/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace DeltaVSoft.RCFProto {

/// <summary>
/// Describes which SSL implementation to use. 
/// </summary>
public enum SslImplementation {
  /// <summary>
  /// Schannel 
  /// </summary>
  Schannel,
  /// <summary>
  /// OpenSSL 
  /// </summary>
  OpenSsl
}

}
