/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace DeltaVSoft.RCFProto {

using System;
using System.Runtime.InteropServices;

/// <summary>
/// Represents a TCP endpoint. 
/// </summary>
public class TcpEndpoint : Endpoint {
  private HandleRef swigCPtr;

  internal TcpEndpoint(IntPtr cPtr, bool cMemoryOwn) : base(RCFProtoPINVOKE.TcpEndpoint_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(TcpEndpoint obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~TcpEndpoint() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          RCFProtoPINVOKE.delete_TcpEndpoint(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  /// <summary>
  /// Constructs a TcpEndpoint from a port number. The IP address defaults to 127.0.0.1 . 
  /// </summary>
  public TcpEndpoint(int port) : this(RCFProtoPINVOKE.new_TcpEndpoint__SWIG_0(port), true) {
    if (RCFProtoPINVOKE.SWIGPendingException.Pending) throw RCFProtoPINVOKE.SWIGPendingException.Retrieve();
  }

  /// <summary>
  /// Constructs a TcpEndpoint from an IP address and port number. 
  /// </summary>
  public TcpEndpoint(string ip, int port) : this(RCFProtoPINVOKE.new_TcpEndpoint__SWIG_1(ip, port), true) {
    if (RCFProtoPINVOKE.SWIGPendingException.Pending) throw RCFProtoPINVOKE.SWIGPendingException.Retrieve();
  }

  /// <summary>
  /// Gets the IP address of the TcpEndpoint. 
  /// </summary>
  public string GetIp() {
    string ret = RCFProtoPINVOKE.TcpEndpoint_getIp(swigCPtr);
    if (RCFProtoPINVOKE.SWIGPendingException.Pending) throw RCFProtoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>
  /// Gets the port number of the TcpEndpoint. 
  /// </summary>
  public int GetPort() {
    int ret = RCFProtoPINVOKE.TcpEndpoint_getPort(swigCPtr);
    if (RCFProtoPINVOKE.SWIGPendingException.Pending) throw RCFProtoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  /// <summary>
  /// Returns a string representation of the TcpEndpoint. 
  /// </summary>
  public string AsString() {
    string ret = RCFProtoPINVOKE.TcpEndpoint_asString(swigCPtr);
    if (RCFProtoPINVOKE.SWIGPendingException.Pending) throw RCFProtoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
