/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace DeltaVSoft.RCFProto {

/// <summary>
/// Describes the transport types used by a RCF connection. 
/// </summary>
public enum TransportType {
  /// <summary>
  /// Unknown 
  /// </summary>
  Unknown,
  /// <summary>
  /// TCP transport 
  /// </summary>
  Tcp,
  /// <summary>
  /// UDP transport 
  /// </summary>
  Udp,
  /// <summary>
  /// Win32 named pipe transport 
  /// </summary>
  Win32NamedPipe,
  /// <summary>
  /// UNIX local domain socket transport 
  /// </summary>
  UnixNamedPipe,
  /// <summary>
  /// HTTP/TCP transport 
  /// </summary>
  Http,
  /// <summary>
  /// HTTPS/TCP transport 
  /// </summary>
  Https
}

}
