/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace DeltaVSoft.RCFProto {

/// <summary>
/// Describes the transport protocols used by a RCF connection. Transport protocols are layered on top of the transport type. 
/// </summary>
public enum TransportProtocol {
  /// <summary>
  /// Unspecified 
  /// </summary>
  Unspecified,
  /// <summary>
  /// Clear text 
  /// </summary>
  Clear,
  /// <summary>
  /// Windows NTLM 
  /// </summary>
  Ntlm,
  /// <summary>
  /// Windows Kerberos 
  /// </summary>
  Kerberos,
  /// <summary>
  /// Windows Negotiate (Kerberos or NTLM) 
  /// </summary>
  Negotiate,
  /// <summary>
  /// SSL 
  /// </summary>
  Ssl
}

}
