/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace DeltaVSoft.RCFProto {

using System;
using System.Runtime.InteropServices;

/// <summary>
/// Represents a UNIX local socket endpoint. Only available on UNIX platforms. 
/// </summary>
public class UnixLocalEndpoint : Endpoint {
  private HandleRef swigCPtr;

  internal UnixLocalEndpoint(IntPtr cPtr, bool cMemoryOwn) : base(RCFProtoPINVOKE.UnixLocalEndpoint_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(UnixLocalEndpoint obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~UnixLocalEndpoint() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          RCFProtoPINVOKE.delete_UnixLocalEndpoint(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  /// <summary>
  /// Constructs a UNIX local socket endpoint with the given name. 
  /// </summary>
  public UnixLocalEndpoint(string socketName) : this(RCFProtoPINVOKE.new_UnixLocalEndpoint(socketName), true) {
    if (RCFProtoPINVOKE.SWIGPendingException.Pending) throw RCFProtoPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
