/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace DeltaVSoft.RCFProto {

using System;
using System.Runtime.InteropServices;

/// <summary>
/// Represents a Win32 named pipe endpoint. Only available on Windows platforms. 
/// </summary>
public class Win32NamedPipeEndpoint : Endpoint {
  private HandleRef swigCPtr;

  internal Win32NamedPipeEndpoint(IntPtr cPtr, bool cMemoryOwn) : base(RCFProtoPINVOKE.Win32NamedPipeEndpoint_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(Win32NamedPipeEndpoint obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~Win32NamedPipeEndpoint() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          RCFProtoPINVOKE.delete_Win32NamedPipeEndpoint(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  /// <summary>
  /// Constructs a Win32 named pipe endpoint with the given pipe name. 
  /// </summary>
  public Win32NamedPipeEndpoint(string pipeName) : this(RCFProtoPINVOKE.new_Win32NamedPipeEndpoint(pipeName), true) {
    if (RCFProtoPINVOKE.SWIGPendingException.Pending) throw RCFProtoPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
