/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace DeltaVSoft.RCFProto {

/// <summary>
/// Win32 certificate store locations. 
/// </summary>
public enum Win32CertificateLocation {
  /// <summary>
  /// Current User 
  /// </summary>
  CurrentUser,
  /// <summary>
  /// Local machine 
  /// </summary>
  LocalMachine
}

}
