/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace DeltaVSoft.RCFProto {

/// <summary>
/// Win32 certificate stores. 
/// </summary>
public enum Win32CertificateStore {
  /// <summary>
  /// Other People 
  /// </summary>
  AddressBook,
  /// <summary>
  /// Third-Party Root Certification Authorities 
  /// </summary>
  AuthRoot,
  /// <summary>
  /// Intermediate Certification Authorities 
  /// </summary>
  CertificateAuthority,
  /// <summary>
  /// Untrusted Certificates 
  /// </summary>
  Disallowed,
  /// <summary>
  /// Personal 
  /// </summary>
  My,
  /// <summary>
  /// Trusted Root Certification Authorities 
  /// </summary>
  Root,
  /// <summary>
  /// Trusted People 
  /// </summary>
  TrustedPeople,
  /// <summary>
  /// Trusted Publishers 
  /// </summary>
  TrustedPublisher
}

}
