/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.deltavsoft.rcfproto;

class _SwigCallbackArgs {
  private long swigCPtr;
  boolean swigCMemOwn;

  _SwigCallbackArgs(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  static long getCPtr(_SwigCallbackArgs obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RCFProtoJNI.delete__SwigCallbackArgs(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMErrorString(String value) {
    RCFProtoJNI._SwigCallbackArgs_mErrorString_set(swigCPtr, this, value);
  }

  public String getMErrorString() {
    return RCFProtoJNI._SwigCallbackArgs_mErrorString_get(swigCPtr, this);
  }

  public void setMCertificatePtr(Certificate value) {
    RCFProtoJNI._SwigCallbackArgs_mCertificatePtr_set(swigCPtr, this, Certificate.getCPtr(value), value);
  }

  public Certificate getMCertificatePtr() {
    long cPtr = RCFProtoJNI._SwigCallbackArgs_mCertificatePtr_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Certificate(cPtr, true);
  }

  public _SwigCallbackArgs() {
    this(RCFProtoJNI.new__SwigCallbackArgs(), true);
  }

}
