/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.deltavsoft.rcfproto;

public enum CertificateImplementationType {
  Unspecified,
  Win32,
  X509;

  final int swigValue() {
    return swigValue;
  }

  static CertificateImplementationType swigToEnum(int swigValue) {
    CertificateImplementationType[] swigValues = CertificateImplementationType.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (CertificateImplementationType swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + CertificateImplementationType.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private CertificateImplementationType() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private CertificateImplementationType(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private CertificateImplementationType(CertificateImplementationType swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

