/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.deltavsoft.rcfproto;

/**
 * Base class of all certificate classes. 
 */
public class Certificate {
  private long swigCPtr;
  private boolean swigCMemOwnBase;

  Certificate(long cPtr, boolean cMemoryOwn) {
    swigCMemOwnBase = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Certificate obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnBase) {
        swigCMemOwnBase = false;
        RCFProtoJNI.delete_Certificate(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  CertificateImplementationType _getType() {
    return CertificateImplementationType.swigToEnum(RCFProtoJNI.Certificate__getType(swigCPtr, this));
  }

  Win32Certificate _downcastToWin32Certificate(Certificate certPtr) {
    long cPtr = RCFProtoJNI.Certificate__downcastToWin32Certificate(swigCPtr, this, Certificate.getCPtr(certPtr), certPtr);
    return (cPtr == 0) ? null : new Win32Certificate(cPtr, true);
  }

  X509Certificate _downcastToX509Certificate(Certificate certPtr) {
    long cPtr = RCFProtoJNI.Certificate__downcastToX509Certificate(swigCPtr, this, Certificate.getCPtr(certPtr), certPtr);
    return (cPtr == 0) ? null : new X509Certificate(cPtr, true);
  }

}
