/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.deltavsoft.rcfproto;

/**
 * Represents a HTTPS endpoint. 
 */
public class HttpsEndpoint extends TcpEndpoint {
  private long swigCPtr;

  HttpsEndpoint(long cPtr, boolean cMemoryOwn) {
    super(RCFProtoJNI.HttpsEndpoint_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  static long getCPtr(HttpsEndpoint obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RCFProtoJNI.delete_HttpsEndpoint(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  /**
   * Constructs an HTTPS endpoint on the given port number. 
   */
  public HttpsEndpoint(int port) {
    this(RCFProtoJNI.new_HttpsEndpoint__SWIG_0(port), true);
  }

  /**
   * Constructs an HTTPS endpoint on the given IP address and port number. 
   */
  public HttpsEndpoint(String ip, int port) {
    this(RCFProtoJNI.new_HttpsEndpoint__SWIG_1(ip, port), true);
  }

}
