/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.deltavsoft.rcfproto;

/**
 * Represents an IP address (IPv4 or IPv6). 
 */
public class IpAddress {
  private long swigCPtr;
  boolean swigCMemOwn;

  IpAddress(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  static long getCPtr(IpAddress obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RCFProtoJNI.delete_IpAddress(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  /**
   * Construct an IP address from a host name 
   */
  public IpAddress(String ip) {
    this(RCFProtoJNI.new_IpAddress__SWIG_0(ip), true);
  }

  /**
   * Construct an IP address from a host name and port. 
   */
  public IpAddress(String ip, int port) {
    this(RCFProtoJNI.new_IpAddress__SWIG_1(ip, port), true);
  }

}
