/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.deltavsoft.rcfproto;

/**
 * Configures log output to be directed to Windows debug output. 
 */
public class LogToDebugWindow extends LogTarget {
  private long swigCPtr;

  LogToDebugWindow(long cPtr, boolean cMemoryOwn) {
    super(RCFProtoJNI.LogToDebugWindow_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  static long getCPtr(LogToDebugWindow obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RCFProtoJNI.delete_LogToDebugWindow(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public LogToDebugWindow() {
    this(RCFProtoJNI.new_LogToDebugWindow(), true);
  }

}
