/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.deltavsoft.rcfproto;

/**
 * Use this class to load a certificate in .pem format. Only applicable to OpenSSL. 
 */
public class PemCertificate extends Certificate {
  private long swigCPtr;
  private boolean swigCMemOwnDerived;

  PemCertificate(long cPtr, boolean cMemoryOwn) {
    super(RCFProtoJNI.PemCertificate_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PemCertificate obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        RCFProtoJNI.delete_PemCertificate(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  /**
   * Loads a .pem certificate, using the given file path and password. 
   */
  public PemCertificate(String pathToCert, String password) {
    this(RCFProtoJNI.new_PemCertificate__SWIG_0(pathToCert, password), true);
  }

  public PemCertificate(String pathToCert) {
    this(RCFProtoJNI.new_PemCertificate__SWIG_1(pathToCert), true);
  }

}
