/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.deltavsoft.rcfproto;

/**
 * Describes which SSL implementation to use. 
 */
public enum SslImplementation {
  /**
   * Schannel 
   */
  Schannel,
  /**
   * OpenSSL 
   */
  OpenSsl;

  final int swigValue() {
    return swigValue;
  }

  static SslImplementation swigToEnum(int swigValue) {
    SslImplementation[] swigValues = SslImplementation.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (SslImplementation swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + SslImplementation.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private SslImplementation() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private SslImplementation(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private SslImplementation(SslImplementation swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

