/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.deltavsoft.rcfproto;

/**
 * Represents a certificate in a Windows certificate store. 
 */
public class StoreCertificate extends Win32Certificate {
  private long swigCPtr;
  private boolean swigCMemOwnDerived;

  StoreCertificate(long cPtr, boolean cMemoryOwn) {
    super(RCFProtoJNI.StoreCertificate_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StoreCertificate obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        RCFProtoJNI.delete_StoreCertificate(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  /**
   * Loads a certificate from a certificate store. 
   */
  public StoreCertificate(Win32CertificateLocation certStoreLocation, Win32CertificateStore certStore, String certName) {
    this(RCFProtoJNI.new_StoreCertificate(certStoreLocation.swigValue(), certStore.swigValue(), certName), true);
  }

  /**
   * Removes the certificate from the store it was loaded from. 
   */
  public void removeFromStore() {
    RCFProtoJNI.StoreCertificate_removeFromStore(swigCPtr, this);
  }

}
