/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.deltavsoft.rcfproto;

/**
 * Iterates over the certificates in a Windows certificate store. 
 */
public class StoreCertificateIterator {
  private long swigCPtr;
  boolean swigCMemOwn;

  StoreCertificateIterator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  static long getCPtr(StoreCertificateIterator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RCFProtoJNI.delete_StoreCertificateIterator(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  /**
   * Constructs a store iterator for the the given certificate location and store. 
   */
  public StoreCertificateIterator(Win32CertificateLocation certStoreLocation, Win32CertificateStore certStore) {
    this(RCFProtoJNI.new_StoreCertificateIterator(certStoreLocation.swigValue(), certStore.swigValue()), true);
  }

  /**
   * Moves to the next certificate in the store. Returns false if there are no more certificates, and true otherwise. 
   */
  public boolean moveNext() {
    return RCFProtoJNI.StoreCertificateIterator_moveNext(swigCPtr, this);
  }

  /**
   * Resets the iterator back to the beginning of the store. 
   */
  public void reset() {
    RCFProtoJNI.StoreCertificateIterator_reset(swigCPtr, this);
  }

  /**
   * Returns the current certificate. 
   */
  public Win32Certificate current() {
    long cPtr = RCFProtoJNI.StoreCertificateIterator_current(swigCPtr, this);
    return (cPtr == 0) ? null : new Win32Certificate(cPtr, true);
  }

}
