/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.deltavsoft.rcfproto;

/**
 * Represents a TCP endpoint. 
 */
public class TcpEndpoint extends Endpoint {
  private long swigCPtr;

  TcpEndpoint(long cPtr, boolean cMemoryOwn) {
    super(RCFProtoJNI.TcpEndpoint_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  static long getCPtr(TcpEndpoint obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RCFProtoJNI.delete_TcpEndpoint(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  /**
   * Constructs a TcpEndpoint from a port number. The IP address defaults to 127.0.0.1 . 
   */
  public TcpEndpoint(int port) {
    this(RCFProtoJNI.new_TcpEndpoint__SWIG_0(port), true);
  }

  /**
   * Constructs a TcpEndpoint from an IP address and port number. 
   */
  public TcpEndpoint(String ip, int port) {
    this(RCFProtoJNI.new_TcpEndpoint__SWIG_1(ip, port), true);
  }

  /**
   * Gets the IP address of the TcpEndpoint. 
   */
  public String getIp() {
    return RCFProtoJNI.TcpEndpoint_getIp(swigCPtr, this);
  }

  /**
   * Gets the port number of the TcpEndpoint. 
   */
  public int getPort() {
    return RCFProtoJNI.TcpEndpoint_getPort(swigCPtr, this);
  }

  /**
   * Returns a string representation of the TcpEndpoint. 
   */
  public String asString() {
    return RCFProtoJNI.TcpEndpoint_asString(swigCPtr, this);
  }

}
