/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.deltavsoft.rcfproto;

public class TransportProtocolList {
  private long swigCPtr;
  boolean swigCMemOwn;

  TransportProtocolList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  static long getCPtr(TransportProtocolList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RCFProtoJNI.delete_TransportProtocolList(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public TransportProtocolList() {
    this(RCFProtoJNI.new_TransportProtocolList__SWIG_0(), true);
  }

  public TransportProtocolList(long n) {
    this(RCFProtoJNI.new_TransportProtocolList__SWIG_1(n), true);
  }

  public long size() {
    return RCFProtoJNI.TransportProtocolList_size(swigCPtr, this);
  }

  public long capacity() {
    return RCFProtoJNI.TransportProtocolList_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    RCFProtoJNI.TransportProtocolList_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return RCFProtoJNI.TransportProtocolList_isEmpty(swigCPtr, this);
  }

  public void clear() {
    RCFProtoJNI.TransportProtocolList_clear(swigCPtr, this);
  }

  public void add(TransportProtocol x) {
    RCFProtoJNI.TransportProtocolList_add(swigCPtr, this, x.swigValue());
  }

  public TransportProtocol get(int i) {
    return TransportProtocol.swigToEnum(RCFProtoJNI.TransportProtocolList_get(swigCPtr, this, i));
  }

  public void set(int i, TransportProtocol val) {
    RCFProtoJNI.TransportProtocolList_set(swigCPtr, this, i, val.swigValue());
  }

}
