/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.deltavsoft.rcfproto;

/**
 * Win32 certificate stores. 
 */
public enum Win32CertificateStore {
  /**
   * Other People 
   */
  AddressBook,
  /**
   * Third-Party Root Certification Authorities 
   */
  AuthRoot,
  /**
   * Intermediate Certification Authorities 
   */
  CertificateAuthority,
  /**
   * Untrusted Certificates 
   */
  Disallowed,
  /**
   * Personal 
   */
  My,
  /**
   * Trusted Root Certification Authorities 
   */
  Root,
  /**
   * Trusted People 
   */
  TrustedPeople,
  /**
   * Trusted Publishers 
   */
  TrustedPublisher;

  final int swigValue() {
    return swigValue;
  }

  static Win32CertificateStore swigToEnum(int swigValue) {
    Win32CertificateStore[] swigValues = Win32CertificateStore.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (Win32CertificateStore swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + Win32CertificateStore.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private Win32CertificateStore() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private Win32CertificateStore(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private Win32CertificateStore(Win32CertificateStore swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

