/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.deltavsoft.rcfproto;

/**
 * Win32 certificate store locations. 
 */
public enum Win32CertificateLocation {
  /**
   * Current User 
   */
  CurrentUser,
  /**
   * Local machine 
   */
  LocalMachine;

  final int swigValue() {
    return swigValue;
  }

  static Win32CertificateLocation swigToEnum(int swigValue) {
    Win32CertificateLocation[] swigValues = Win32CertificateLocation.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (Win32CertificateLocation swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + Win32CertificateLocation.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private Win32CertificateLocation() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private Win32CertificateLocation(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private Win32CertificateLocation(Win32CertificateLocation swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

